export const primaryColor = '#73C6CD'
export const secondaryColor = '#F3C046'
export const darkNeutralColor = '#343140'
export const lightNeutralColor = '#f2f3f7'
export const primaryColorVariant = '#62D4CE'
export const variantColor = '#8E85BB'
